name: Terraform CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code  
        uses: actions/checkout@v3

      - name: Terraform Validate
        id: validate
        run: terraform validate
        env:
            token: ${{ secrets.TOKEN }}
            cloud_id: ${{ secrets.CLOUD_ID }}
            folder_id: ${{ secrets.FOLDER_ID }}
            site_url: ${{ secrets.SITE_URL }}
            db_user: ${{ secrets.DB_USER }}
            db_pwd: ${{ secrets.DB_PWD }}
            datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
            ssh_user: ${{ secrets.SSH_USER }}
            ssh_path: ${{ secrets.SSH_PATH }}

            